[default]
DEBUG = true
HOST = '0.0.0.0'
PORT = '8000'

[development]
DEBUG = true
POSTGRES_DB_NAME = "idea"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "Prasan123#"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
FRONTEND_URL = "http://localhost:3000"

[staging]
DEBUG = true
POSTGRES_DB_NAME = "idea"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "Prasan123#"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
FRONTEND_URL = "http://localhost:3000"

[production]
DEBUG = false
POSTGRES_DB_NAME = "idea"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "Prasan123#"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
FRONTEND_URL = "http://localhost:3000"